"""empty message

Revision ID: 3f123ff04e7e
Revises: 
Create Date: 2021-05-28 14:51:20.104304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f123ff04e7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.String(length=8), nullable=False),
    sa.Column('book_name', sa.String(length=255), nullable=False),
    sa.Column('book_genre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=8), nullable=False),
    sa.Column('password', sa.String(length=8), nullable=False),
    sa.Column('user_name', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('borrowbook',
    sa.Column('keyid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=8), nullable=True),
    sa.Column('book_id', sa.String(length=8), nullable=True),
    sa.Column('frag', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('keyid')
    )
    op.create_table('cardhistory',
    sa.Column('cardhistory_id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=8), nullable=True),
    sa.Column('history_date', sa.Integer(), nullable=False),
    sa.Column('chargemoney', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cardhistory_id')
    )
    op.create_table('cardinfo',
    sa.Column('cardinfo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=8), nullable=True),
    sa.Column('card_number', sa.String(length=16), nullable=True),
    sa.Column('card_key', sa.String(length=3), nullable=True),
    sa.Column('card_date', sa.Date(), nullable=True),
    sa.Column('card_name', sa.String(length=10), nullable=True),
    sa.Column('user_money', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cardinfo_id')
    )
    op.create_table('reserve',
    sa.Column('reserve_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=8), nullable=True),
    sa.Column('reserve_date', sa.Date(), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reserve_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserve')
    op.drop_table('cardinfo')
    op.drop_table('cardhistory')
    op.drop_table('borrowbook')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
